--- #YAML:1.0
name:                POE-Component-WebService-Validator-HTML-W3C
version:             0.03
abstract:            a non-blocking L<POE>
license:             ~
author:              
    - Zoffix Znet <zoffix@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          1.04
    POE:                           0.9999
    POE::Filter::Line:             1.192
    POE::Filter::Reference:        1.2187
    POE::Wheel::Run:               1.2179
    Test::More:                    0.74
    WebService::Validator::HTML::W3C: 0.22
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
